const categories=[
{id:'outdoor-parks',name:'Outdoor Parks',desc:'Fresh air, open spaces & a change of scenery.',icon:'♧',tint:'#dbeee6',ink:'#186b50',items:[['Lakeside picnic park','A sample outdoor listing with room for a family picnic and a stroll by the water.',['Outdoors','Picnic areas']],['Woodland walking trails','A sample nature outing for a relaxed walk and time together outdoors.',['Outdoors','Walking']]]},
{id:'indoor-parks',name:'Indoor Parks',desc:'All the fun, whatever the weather.',icon:'◉',tint:'#ddeaf5',ink:'#336a9d',items:[['Indoor adventure park','A sample indoor activity listing with play spaces for an energetic day out.',['Indoors','Active play']],['Family play center','A sample play-center listing for a family outing on a rainy day.',['Indoors','Family activity']]]},
{id:'amusement-parks',name:'Amusement Parks',desc:'Rides, excitement & big family memories.',icon:'☼',tint:'#ffedcf',ink:'#a9651b',items:[['Family amusement park','A sample listing for rides and a day of family entertainment.',['Rides','Family activity']],['Mini adventure park','A sample outing with smaller attractions and activities.',['Activities','Outdoors']]]},
{id:'zoos-farms',name:'Zoos & Farms',desc:'Meet the animals. Explore something new.',icon:'♞',tint:'#f1e6d9',ink:'#895e34',items:[['Animal discovery farm','A sample farm listing for an animal-themed family visit.',['Animals','Outdoors']],['Wildlife park','A sample listing for a day discovering wildlife.',['Animals','Walking']]]},
{id:'museums',name:'Museums & Discovery',desc:'Hands-on discoveries for curious minds.',icon:'▥',tint:'#e9e4f5',ink:'#69518d',items:[['Hands-on discovery museum','A sample museum listing with activities designed to spark curiosity.',['Indoors','Discovery']],['Transport museum','A sample outing to explore vehicles and their stories.',['Indoors','Learning']]]},
{id:'activities',name:'Family Activities',desc:'A little friendly competition. Lots of fun.',icon:'◎',tint:'#dceff0',ink:'#2b7b80',items:[['Mini golf outing','A sample activity listing for a relaxed family game.',['Games','Family activity']],['Bowling afternoon','A sample indoor outing for time together at the lanes.',['Indoors','Games']]]}
];
const app=document.querySelector('#app');let query='';
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function search(){return `<label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Search outings or categories" aria-label="Search outings or categories" value="${esc(query)}"></label>`}
function outing(c,i){const x=c.items[i];return `<a class="outing" href="#/category/${c.id}/${i}"><span class="sample">SAMPLE OUTING</span><h2>${x[0]}</h2><p>${x[1]}</p><div class="tags">${x[2].map(t=>`<span>${t}</span>`).join('')}</div><span class="view">View outing details</span></a>`}
function homeResults(){const q=query.toLowerCase().trim();if(q){let matches=categories.flatMap(c=>c.items.map((x,i)=>({c,x,i}))).filter(({c,x})=>[c.name,...x.flat()].join(' ').toLowerCase().includes(q));return `<div class="section-label"><h2>Search results</h2><span>${matches.length} sample outings</span></div><div class="list">${matches.map(({c,i})=>outing(c,i)).join('')||'<div class="empty"><h2>No outings found</h2><p>Try a different word, such as indoor, farm, or park.</p></div>'}</div>`}return `<div class="section-label"><h2>Explore by category</h2><span>6 sample categories</span></div><div class="grid">${categories.map((c,i)=>`<a class="category" href="#/category/${c.id}" style="--tint:${c.tint};--ink:${c.ink}"><div class="category-top">${i===0?'<img src="park.jpg" alt="A green park beside a lake" width="700" height="400">':`<span class="glyph" aria-hidden="true">${c.icon}</span>`}<span class="number">0${i+1}</span></div><div class="category-body"><h3>${c.name}</h3><p>${c.desc}</p><div class="card-foot"><span>2 sample outings</span><strong>Explore category</strong></div></div></a>`).join('')}</div>`}
function render(){const parts=location.hash.slice(1).split('/').filter(Boolean);const c=categories.find(c=>c.id===parts[1]);if(!parts.length){document.title='Outings Guide';app.innerHTML=`<div class="intro"><div><p class="eyebrow">Make a day of it</p><h1>Where shall we <em>go?</em></h1><p class="sub">Find your next family outing, one category at a time.</p></div>${search()}</div><section id="results">${homeResults()}</section>`;document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;document.querySelector('#results').innerHTML=homeResults()});return}
if(parts[0]!=='category'||!c||parts.length>3||(parts.length===3&&!c.items[parts[2]])){app.innerHTML='<div class="empty"><h1>Page not found</h1><a class="back" href="#/">Browse categories</a></div>';return}
const crumb=`<nav class="crumb" aria-label="Breadcrumb"><a href="#/">All categories</a><span>/</span>${parts.length===3?`<a href="#/category/${c.id}">${c.name}</a><span>/</span><span>Outing details</span>`:`<span>${c.name}</span>`}</nav>`;
if(parts.length===2){document.title=c.name+' | Outings Guide';app.innerHTML=crumb+`<div class="intro"><div><p class="eyebrow">Explore the category</p><h1>${c.name}</h1><p class="sub">${c.desc}</p></div></div><div class="section-label"><h2>Outings in this category</h2><span>2 sample listings</span></div><div class="list">${c.items.map((x,i)=>outing(c,i)).join('')}</div>`;return}
const x=c.items[parts[2]];document.title=x[0]+' | Outings Guide';app.innerHTML=crumb+`<div class="intro"><div><p class="eyebrow">${c.name}</p><h1>${x[0]}</h1><span class="sample">SAMPLE OUTING · NOT A REAL VENUE LISTING</span></div></div><div class="detail"><section class="panel"><h2>About this outing</h2><p>${x[1]}</p><div class="tags">${x[2].map(t=>`<span>${t}</span>`).join('')}</div><p>The venue’s description and information from the booklet will appear here once its listings are added.</p><a class="back" href="#/category/${c.id}">Back to ${c.name}</a></section><section class="panel"><h2>Plan your visit</h2><dl class="facts">${['Address','Opening hours','Admission prices','Phone & website'].map(t=>`<div><dt>${t}</dt><dd>To be added from the booklet</dd></div>`).join('')}</dl></section></div>`}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
